[package]
name = "bevytest"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.1", features = ["dynamic_linking"] }
env_logger = "0.11.6"
renet = "1.0.0"
renet_netcode = "1.0.0"
renet_steam = "1.0.0"
renetcode = "1.0.0"
steamworks = "0.11.0"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
